version: "3.8"
services:

  nginx1:
    image: nginx
    container_name: nginx-1
    networks:
     - nginx-bridge
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nginx-vol
        target: /usr/share/nginx/html
      
  nginx2:
    image: nginx
    container_name: nginx-2
    networks:
     - nginx-bridge
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: /home/ec2-user/volume_content
        target: /usr/share/nginx/html

volumes:
  nginx-vol:
    name: nginx-volume

networks:
  nginx-bridge:
    name: nginx-network