apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-datafence-deployment
  labels:
    name: df-depl
spec:
  replicas: 1
  template:
    metadata:
      name: devops-datafence-pod-rs
      labels:
        app: df-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /datafence
              name: nginx-data
          resources:
            requests:
              memory: "128Mi"
              cpu: 0.2
      volumes:
      - name: nginx-data
        awsElasticBlockStore:
          volumeID: <EBS_VOLUME_ID>
          fsType: ext4
  selector:
    matchLabels:
      app: df-pod

      