apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: devops-datafence-replica-set
  labels:
    name: df-rs
spec:
  template:
    metadata:
      name: devops-datafence-pod-rs
      labels:
        app: df-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
  replicas: 2
  selector:
    matchLabels:
      app: df-pod