apiVersion: v1
kind: Pod
metadata:
  name: devops-datafence-pod-sa
  namespace: devops-df-dev
  labels:
    app: df-pod-sa
spec:
  containers:
    - name: amazon-linux-ami
      image: amazonlinux
      command: ["sleep", "1000"]
  serviceAccount: devops-df-sa