apiVersion: v1
kind: Service
metadata:
  name: devops-datafence-service-lb
  labels:
    name: df-svc-lb
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 12145
  selector:
    app: df-pod

    