AWSTemplateFormatVersion: 2010-09-09
Description: "Template for automating Downstream etl"

Parameters:

  Env:
    Type: String
    Description: Name of Env (dev, qa, uat, prod, devops)
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
      - devops
    Default: devops

  Team:
    Type: String
    Default: datafence

  SparkJobPythonVersion:
    Type: String
    Description: Version of Python for Spark Job
    Default: '3'
    
  SparkJobGlueVersion:
    Type: String
    Description: Glue Version for Spark Job
    Default: '1.0'
    
  SparkJobMaxCapacity:
    Type: String
    Description: Spark Job Max Capacity
    Default: '5'
    
  SparkJobMaxRetries:
    Type: String
    Description: Spark Job Max Reties
    Default: '1'

  SparkJobName:
    Type: String
    Description: Spark Job Name
    Default: spark-job
    
  SparkJobTimeout:
    Type: String
    Description: The job timeout in minutes.
    Default: '5'

  # GlueArtifactsBucket:
  #   Type: String
  #   Description: S3 Bucket for Glue Artifacts
  #   Default: devops-datafence-us-east-1-175908995626-s3-bucket-cf

  ImportStackName:
    Type: String
    Description: Stack Name from where to import values
    Default: devops-datafence-upstream-stack


Resources:

  SparkGlueJob:    
    Type: AWS::Glue::Job
    Properties: 
      Command: 
        Name: glueetl
        PythonVersion: !Ref SparkJobPythonVersion
        ScriptLocation:
          Fn::Join:
            - ""
            - - "s3://"
              - Fn::ImportValue: !Sub ${ImportStackName}-S3Bucket
              - /devops-datafence-transformation.py
      Description: Serverless Spark Job
      GlueVersion: !Ref SparkJobGlueVersion
      MaxCapacity: !Ref SparkJobMaxCapacity
      MaxRetries: !Ref SparkJobMaxRetries
      Name: !Sub ${Env}-${Team}-${SparkJobName}
      Role: !GetAtt SparkJobRole.Arn
      Timeout: !Ref SparkJobTimeout
     
  SparkJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-${Team}-spark-job-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com      
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess