AWSTemplateFormatVersion: 2010-09-09
Description: "Template for automating SSM Parameters & Secrets Manager"

Parameters:

  Env:
    Type: String
    Description: Name of Env (dev, qa, uat, prod, devops)
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
      - devops
    Default: devops


  SparkJobPythonVersion:
    Type: String
    Description: Version of Python for Spark Job
    Default: '3'

  SparkJobMaxCapacity:
    Type: String
    NoEcho: True
    Description: Spark Job Max Capacity

Resources:

  SparkJobPythonVersionSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SparkJobPythonVersion
      Value: !Ref SparkJobPythonVersion
      Type: String
      Tier: Standard
      Tags:
        Env: !Ref Env

  SparkJobMaxCapacitySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: "Secret Manager secret for SparkJobMaxCapacity"
      Name: SparkJobMaxCapacitySecret
      SecretString: !Sub "{\"capacity\": \"${SparkJobMaxCapacity}\"}"

  SparkJobMaxCapacitySecretArnSSMParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: "SSM Parameter for SparkJobMaxCapacity Secret Arn"
      Name: SparkJobMaxCapacitySecretArn
      Tags:
        Env: !Ref Env
      Tier: Standard
      Type: String
      Value: !Ref SparkJobMaxCapacitySecret
