version: 0.0
os: linux
files:
  - source: devops-df-build-artifact.zip
    destination: /home/ubuntu/datafence_app/
hooks:
  AfterInstall:
    - location: uncompress
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_flask
      timeout: 300
      runas: root
    - location: start_node
      timeout: 300
      runas: root